services:
  listings-api:
    build:
      context: api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - api/.env
    environment:
      - DB_HOST=db
      - APP_NAME=listings-api
      - APP_PORT=3000
    depends_on:
      - db
  listings-state-pm:
    build:
      context: api
      dockerfile: Dockerfile
    env_file:
      - api/.env
    environment:
      - DB_HOST=db
      - APP_NAME=listings-state-pm
    depends_on:
      - db
  images-api:
    build:
      context: api
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    env_file:
      - api/.env
    environment:
      - DB_HOST=db
      - APP_NAME=images-api
      - APP_PORT=3002
    depends_on:
      - db
  db:
    image: postgres:17
    container_name: postgres_container
    restart: always
    shm_size: 128mb
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db-init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  postgres_data:
